package.json, server.js
Made basic files including an empty env and cs/js folders in the public root.
=> Uploading all basic file structures.

controllers/apiRoutes/index.js, controllers/apiRoutes/logRoutes.js, controllers/apiRoutes/ticketRoutes.js, controllers/apiRoutes/userRoutes.js
Finished setup. Should be able to just pull this into the main branch for the apiRoutes.
=> Api routes setup

controllers/homeRoutes.js
changed the render page also the attributes
=> renderdash and changed attributes

package.json, views/dashboard.handlebars
added "watch" command for nodemon
started working on dashboard ticket link
=> added "watch" command for nodemon

views/partials/new-ticket.handlebars
Added HTML and CSS using bootstrap to add a new modal/form which will be shown when the user is creating a new ticket. Has subject, description, and urgency field (urgency is a dropdown menu with 3 options for "Level").
=> added a new modal partial to views

package.json, public/js/dashboard.js, views/dashboard.handlebars, views/layouts/main.handlebars
fixed naming so table now displays tickets
changed table head color
=> fixed "this." naming 

views/dashboard.handlebars
This is the implementation for issue #91
=> Implemented the format_date helper function in the dashboard.handlebars file.

views/partials/new-ticket.handlebars
changed id from 'newTicket' to 'modal'
=> small changes that I overlooked on first commit

public/js/createTicket.js, views/dashboard.handlebars
changed addButton to addBtn
called the new-ticket.handlebars partial in the dashboard.handlebars
=> few more small changes

controllers/homeRoutes.js, seeds/ticketData.json, seeds/userData.json, utils/helpers.js, views/ticket.handlebars
Ticket handlebar now displays Ticket data that is dynamically generated - which uses two new functions added to Helper. Updated seeds for testing functionality, and added an admin account seed for when deployed.
=> Joshua - Ticket Handlebar/ Helper/ Seed update

controllers/apiRoutes/logRoutes.js
This is the implementation for Issue #103
=> Server-Side API post route for Ticket added.

public/js/dashboard.js, server.js, utils/helpers.js, views/dashboard.handlebars
claim button added when status is open
=> added dynamic claim button

views/layouts/main.handlebars
Hey, I had to update this with another brief clean-up change, Nothing major.
=> Logan issue100

package-lock.json, package.json, public/css/jass.css, views/partials/new-ticket.handlebars
-added dropdown selector
-style changes to modal
=> more modal changes

controllers/homeRoutes.js
=> Added the required as keys and tested it with a console log everything is in place. Pushing now.

public/css/jass.css, public/js/createTicket.js, views/partials/new-ticket.handlebars
should work as intended now, as a drawer on the right side of the screen
=> finished modal styling

public/js/chat.js, public/js/createTicket.js, views/partials/ticket-chat.handlebars
-Implemented the logic for the toggleHidden function which activates on a click event on anything with the hide-eye class.
-This function sends a post request to the server to update the hidden value for the selected chat log
-If the put request was successful it will reload the page if not it will throw an error
-By reloading the page this should act as a way to toggle between hidden and unhidden
-Did an extremely small refactor of the createTicket.js by updating some of the query selectors and comments
=> Hidden Span Toggle Listener and createTicket.js refactor

views/dashboard.handlebars
add seperate client and tech columns
now will display both client and tech
=> add seperate client and tech columns

public/js/chat.js
- This is a function that will submit new chat message in the ticket chat view.
-This function will run on a submit event listener on the form
(Forgot to add this will be pushing that addition directly after this pull request)
-It captures the ticketId from the window and the user input message and checkbox then sends that information as a POST request
-If the post is successful the response back is set to the variable data and then sent to the renderNewMessage function that has yet to be coded
-If it fails it alerts the user that message failed to post
=> Implemented the Submit New Chat Message function

public/js/closeModal.js, views/partials/new-ticket.handlebars
-added close button functionality
-added submit request functionality
=> modal functionality completed

utils/helpers.js
updated renderStatus and renderUrgencyOptions so that values reflect proper string value
=> modify functions in helper.js patch

public/js/chat.js, views/partials/ticket-chat.handlebars
-Christopher was pretty swamped with other work and asked me if I could help him with coding this renderNewMessage function
-This function renders the new chat message only on successful POST response from the server
-It takes this server data as an argument for the function
-The function itself creates two divs and one p element
-These elements will hold the chat message and the hidden icon
-It contains conditional logic to change the appearance of the hidden icon based on wether or not the server response indicated the message was hidden or whown
-It then appends the log_text and the hidden icon to a message container
-This message container then gets appended to the message list
!!IMPORTANT!!
-In order for this function to work properly there needs to exist an element with the ID of …
=> Render Chat Messages Function

public/js/dashboard.js
-added event listeners for all claim buttons
-added fetch call to put status of claimed
=> added fetch put to claim button

controllers/homeRoutes.js, public/css/style.css, public/js/dashboard.js, utils/helpers.js, views/about.handlebars, views/dashboard.handlebars
Table won't show if no tickets exist
added "data-id" to button
=> Table won't show if no tickets exist
